using UnityEngine;
using System.Collections;


public class UISpriteManager : MonoBehaviour
{
	public Sprite animalHideSprite;
	public Sprite anvilImpactSprite;
	public Sprite bedSprite;
	public Sprite brickPileSprite;
	public Sprite brokenBoneSprite;
	public Sprite brutalHelmSprite;
	public Sprite foodMeatChickenSprite;
	public Sprite mushroomPosionSprite;
	public Sprite defensiveWallSprite;
	public Sprite mineGemSprite;
	public Sprite mineStoneSprite;
	public Sprite foodEatSprite;
	public Sprite auraOutlineSprite;
	public Sprite mailEnvelopeSprite;
	public Sprite exitDoorSprite;
	public Sprite farmPlantSprite;
	public Sprite guardSprite;
	public Sprite constructionHammerSprite;
	public Sprite grassSprite;
	public Sprite claimLandSprite;
	public Sprite holySymbolSprite;
	public Sprite dogSprite;
	public Sprite homeSprite;
	public Sprite patrolSprite;
	public Sprite foodKnifeForkSprite;
	public Sprite crownSprite;
	public Sprite lockedChestSprite;
	public Sprite lungsSprite;
	public Sprite magnifyGlassSprite;
	public Sprite mailboxSprite;
	public Sprite foodMeatSprite;
	public Sprite familySprite;
	public Sprite wrenchSprite;
	public Sprite mushroomSprite;
	public Sprite bookOpenSprite;
	public Sprite policeSprite;
	public Sprite holyPraySprite;
	public Sprite presentSprite;
	public Sprite prisonerSprite;
	public Sprite rankPrivateSprite;
	public Sprite publicSpeakerSprite;
	public Sprite rabbitSprite;
	public Sprite radioactiveSprite;
	public Sprite orderRallySprite;
	public Sprite rankSergeantSprite;
	public Sprite wrenchRepairSprite;
	public Sprite waterBottleGlassSprite;
	public Sprite stonePileSprite;
	public Sprite orderAttackSprite;
	public Sprite towerFlagSprite;
	public Sprite tradeSprite;
	public Sprite treeBranchSprite;
	public Sprite watchtowerSprite;
	public Sprite wolfHeadSprite;
	public Sprite wolfHowlSprite;
	public Sprite crateSprite;
	public Sprite firePutOutSprite;
	public Sprite fireLightSprite;
	public Sprite foodGrainSprite;
	public Sprite waterCanSprite;
	public Sprite waterDrinkSprite;
	public Sprite throneSprite;


	public static Sprite animalHide;
	public static Sprite anvilImpact;
	public static Sprite bed;
	public static Sprite brickPile;
	public static Sprite brokenBone;
	public static Sprite brutalHelm;
	public static Sprite foodMeatChicken;
	public static Sprite mushroomPosion;
	public static Sprite defensiveWall;
	public static Sprite mineGem;
	public static Sprite mineStone;
	public static Sprite foodEat;
	public static Sprite auraOutline;
	public static Sprite mailEnvelope;
	public static Sprite exitDoor;
	public static Sprite farmPlant;
	public static Sprite guard;
	public static Sprite constructionHammer;
	public static Sprite grass;
	public static Sprite claimLand;
	public static Sprite holySymbol;
	public static Sprite dog;
	public static Sprite home;
	public static Sprite patrol;
	public static Sprite foodKnifeFork;
	public static Sprite crown;
	public static Sprite lockedChest;
	public static Sprite lungs;
	public static Sprite magnifyGlass;
	public static Sprite mailbox;
	public static Sprite foodMeat;
	public static Sprite family;
	public static Sprite wrench;
	public static Sprite mushroom;
	public static Sprite bookOpen;
	public static Sprite police;
	public static Sprite holyPray;
	public static Sprite present;
	public static Sprite prisoner;
	public static Sprite rankPrivate;
	public static Sprite publicSpeaker;
	public static Sprite rabbit;
	public static Sprite radioactive;
	public static Sprite orderRally;
	public static Sprite rankSergeant;
	public static Sprite wrenchRepair;
	public static Sprite waterBottleGlass;
	public static Sprite stonePile;
	public static Sprite orderAttack;
	public static Sprite towerFlag;
	public static Sprite trade;
	public static Sprite treeBranch;
	public static Sprite watchtower;
	public static Sprite wolfHead;
	public static Sprite wolfHowl;
	public static Sprite crate;
	public static Sprite firePutOut;
	public static Sprite fireLight;
	public static Sprite foodGrain;
	public static Sprite waterCan;
	public static Sprite waterDrink;
	public static Sprite throne;

	

	private void Start()
	{
		animalHide = animalHideSprite;
		anvilImpact = anvilImpactSprite;
		bed = bedSprite;
		brickPile = brickPileSprite;
		brokenBone = brokenBoneSprite;
		brutalHelm = brutalHelmSprite;
		foodMeatChicken = foodMeatChickenSprite;
		mushroomPosion = mushroomPosionSprite;
		defensiveWall = defensiveWallSprite;
		mineGem = mineGemSprite;
		mineStone = mineStoneSprite;
		foodEat = foodEatSprite;
		auraOutline = auraOutlineSprite;
		mailEnvelope = mailEnvelopeSprite;
		exitDoor = exitDoorSprite;
		farmPlant = farmPlantSprite;
		guard = guardSprite;
		constructionHammer = constructionHammerSprite;
		grass = grassSprite;
		claimLand = claimLandSprite;
		holySymbol = holySymbolSprite;
		dog = dogSprite;
		home = homeSprite;
		patrol = patrolSprite;
		foodKnifeFork = foodKnifeForkSprite;
		crown = crownSprite;
		lockedChest = lockedChestSprite;
		lungs = lungsSprite;
		magnifyGlass = lungsSprite;
		mailbox = mailboxSprite;
		foodMeat = foodMeatSprite;
		family = foodMeatSprite;
		wrench = wrenchSprite;
		mushroom = mushroomSprite;
		bookOpen = bookOpenSprite;
		police = policeSprite;
		holyPray = holyPraySprite;
		present = presentSprite;
		prisoner = prisonerSprite;
		rankPrivate = rankPrivateSprite;
		publicSpeaker = publicSpeakerSprite;
		rabbit = rabbitSprite;
		radioactive = rabbitSprite;
		orderRally = orderRallySprite;
		rankSergeant = rankSergeantSprite;
		wrenchRepair = wrenchRepairSprite;
		waterBottleGlass = waterBottleGlassSprite;
		stonePile = stonePileSprite;
		orderAttack = orderAttackSprite;
		towerFlag = towerFlagSprite;
		trade = tradeSprite;
		treeBranch = treeBranchSprite;
		watchtower = watchtowerSprite;
		wolfHead = wolfHeadSprite;
		wolfHowl = wolfHowlSprite;
		crate = wolfHowlSprite;
		firePutOut = firePutOutSprite;
		fireLight = fireLightSprite;
		foodGrain = foodGrainSprite;
		waterCan = waterCanSprite; ;
		waterDrink = waterDrinkSprite;
		throne = throneSprite;
	}
}